{{- if .Values.global.dnsZone }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    {{- include "knowledge-graph-analytics.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: allocs16@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
