#!/usr/bin/env python3
"""Probe the evidence migration's upgrade and downgrade delta in isolation.

This is deliberately not an ``alembic upgrade head`` check.  The historical
revision chain is measured separately and remains advisory because it contains
known bootstrap debt.  This probe creates only the two objects required to
exercise ``evidence_prov_20260816`` from its exact parent revision, runs the
real Alembic commands, verifies the PostgreSQL column metadata, and removes its
generated database in a ``finally`` block.
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import signal
import subprocess
import sys
from collections.abc import Iterable, Iterator, Mapping, Sequence
from contextlib import contextmanager
from pathlib import Path
from typing import Any, TypeAlias, cast
from urllib.parse import quote

import psycopg2  # type: ignore[import-untyped]
from psycopg2 import sql  # type: ignore[import-untyped]
from sqlalchemy.engine import URL, make_url

PARENT_REVISION = "i9j0k1l2m3n4"
TARGET_REVISION = "evidence_prov_20260816"
TABLE_NAME = "stance_classifications"
SCRATCH_DATABASE_PREFIX = "ci_evidence_delta_"
CONNECT_TIMEOUT_SECONDS = 15
ALEMBIC_TIMEOUT_SECONDS = 120
STATEMENT_TIMEOUT_MS = 30_000

ColumnRow: TypeAlias = tuple[str, str, int | None, str]

EXPECTED_COLUMNS: dict[str, tuple[str, int | None]] = {
    "claim_text": ("text", None),
    "source_content_hash": ("character varying", 64),
    "inference_model_version": ("character varying", 100),
}

_SCRATCH_DATABASE_RE = re.compile(
    rf"^{re.escape(SCRATCH_DATABASE_PREFIX)}[0-9]+_[a-z0-9_]+_[0-9a-f]{{8}}$"
)


class ProbeError(RuntimeError):
    """Raised when the targeted migration contract is not satisfied."""


class ProbeInterrupted(ProbeError):
    """Raised after a deferred termination signal and guarded cleanup."""


def scratch_database_name(label: str = "probe") -> str:
    """Return a unique, deliberately recognisable PostgreSQL database name."""
    safe_label = re.sub(r"[^a-z0-9]+", "_", label.lower()).strip("_") or "probe"
    safe_label = safe_label[:24].rstrip("_") or "probe"
    return f"{SCRATCH_DATABASE_PREFIX}{os.getpid()}_{safe_label}_{secrets.token_hex(4)}"


def is_safe_scratch_database_name(name: str) -> bool:
    """Allow destructive cleanup only for names generated by this probe."""
    return bool(_SCRATCH_DATABASE_RE.fullmatch(name))


def verify_added_columns(rows: Iterable[ColumnRow]) -> None:
    """Verify the exact nullable PostgreSQL types added by the migration."""
    observed = {
        name: (data_type, character_maximum_length, is_nullable)
        for name, data_type, character_maximum_length, is_nullable in rows
    }
    for name, (expected_type, expected_length) in EXPECTED_COLUMNS.items():
        expected = (expected_type, expected_length, "YES")
        actual = observed.get(name)
        if actual != expected:
            raise ProbeError(
                f"{TABLE_NAME}.{name} metadata mismatch: "
                f"expected {expected!r}, got {actual!r}"
            )


def verify_columns_absent(column_names: Iterable[str]) -> None:
    """Verify neither migration column remains after the downgrade."""
    unexpected = sorted(set(column_names).intersection(EXPECTED_COLUMNS))
    if unexpected:
        raise ProbeError(
            f"downgrade left migration column(s) on {TABLE_NAME}: "
            f"{', '.join(unexpected)}"
        )


def alembic_environment(
    database_url: str, base_environment: Mapping[str, str] | None = None
) -> dict[str, str]:
    """Build an Alembic environment that cannot fall through to managed DBs."""
    environment = dict(os.environ if base_environment is None else base_environment)
    environment["DATABASE_URL"] = database_url
    # env.py prefers SUPABASE_DB_URL. An empty value makes the target explicit.
    environment["SUPABASE_DB_URL"] = ""
    environment.setdefault("ENVIRONMENT", "testing")
    backend_root = Path(__file__).resolve().parents[2] / "backend"
    python_path = environment.get("PYTHONPATH")
    environment["PYTHONPATH"] = (
        str(backend_root)
        if not python_path
        else os.pathsep.join((str(backend_root), python_path))
    )
    return environment


def postgres_url_from_environment(
    environment: Mapping[str, str] | None = None,
) -> str:
    """Render a PostgreSQL URL from standard ``PG*`` fields safely.

    The shell wrapper deliberately passes credentials as environment values.
    ``URL.create`` performs the escaping, so characters such as ``@``, ``/``,
    ``:``, and ``%`` cannot alter the host or database selected by the URL.
    """
    source = os.environ if environment is None else environment
    port_value = source.get("PGPORT", "5432")
    try:
        port = int(port_value)
    except ValueError as exc:
        raise ProbeError("PGPORT must be an integer") from exc
    return cast(
        str,
        URL.create(
            drivername="postgresql",
            username=source.get("PGUSER", "postgres"),
            password=source.get("PGPASSWORD", ""),
            host=source.get("PGHOST", "127.0.0.1"),
            port=port,
            database=source.get("PGDATABASE", "postgres"),
        ).render_as_string(hide_password=False),
    )


def _scratch_database_url(admin_database_url: str, database_name: str) -> str:
    parsed = make_url(admin_database_url)
    if parsed.drivername not in {"postgresql", "postgresql+psycopg2"}:
        raise ProbeError(
            "targeted evidence migration probe requires a PostgreSQL admin URL"
        )
    return cast(
        str, parsed.set(database=database_name).render_as_string(hide_password=False)
    )


def _redact_credentials(message: str, database_urls: Iterable[str]) -> str:
    """Remove raw and URL-encoded passwords from diagnostic text."""
    secrets_to_redact: set[str] = set()
    rendered_urls: set[str] = set()
    for database_url in database_urls:
        if not database_url:
            continue
        rendered_urls.add(database_url)
        try:
            parsed = make_url(database_url)
        except Exception:
            parsed = None
        if parsed is not None:
            rendered_urls.add(parsed.render_as_string(hide_password=False))
            rendered_urls.add(parsed.render_as_string(hide_password=True))
            if parsed.password:
                secrets_to_redact.add(parsed.password)
                secrets_to_redact.add(quote(parsed.password, safe=""))

        # The CLI accepts a URL for backwards compatibility.  Recover the raw
        # authority password even when unescaped punctuation makes that URL
        # impossible for a URL parser to normalize safely.
        if "://" in database_url and "@" in database_url:
            authority = database_url.split("://", 1)[1].rsplit("@", 1)[0]
            if ":" in authority:
                raw_password = authority.split(":", 1)[1]
                if raw_password:
                    secrets_to_redact.add(raw_password)

    redacted = message
    for rendered_url in sorted(rendered_urls, key=len, reverse=True):
        if rendered_url:
            redacted = redacted.replace(rendered_url, "<database-url>")
    for secret in sorted(secrets_to_redact, key=len, reverse=True):
        redacted = redacted.replace(secret, "<redacted>")
    return redacted


def _connect(database_url: str):  # type: ignore[no-untyped-def]
    return psycopg2.connect(
        database_url,
        connect_timeout=CONNECT_TIMEOUT_SECONDS,
        options=f"-c statement_timeout={STATEMENT_TIMEOUT_MS}",
    )


def _create_database(admin_connection, database_name: str) -> None:  # type: ignore[no-untyped-def]
    """Create only a generated scratch database, never an arbitrary target."""
    if not is_safe_scratch_database_name(database_name):
        raise ProbeError(
            f"refusing to create unrecognised scratch database {database_name!r}"
        )
    admin_connection.autocommit = True
    with admin_connection.cursor() as cursor:
        cursor.execute(
            sql.SQL("CREATE DATABASE {} WITH TEMPLATE template0").format(
                sql.Identifier(database_name)
            )
        )


def _create_prior_state(connection) -> None:  # type: ignore[no-untyped-def]
    """Create only the explicit parent-state objects needed by the migration."""
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE alembic_version (
                version_num VARCHAR(32) NOT NULL
            )
            """)
        cursor.execute(
            "INSERT INTO alembic_version (version_num) VALUES (%s)",
            (PARENT_REVISION,),
        )
        cursor.execute("""
            CREATE TABLE stance_classifications (
                id UUID PRIMARY KEY
            )
            """)
    connection.commit()


def _column_rows(connection) -> list[ColumnRow]:  # type: ignore[no-untyped-def]
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name, data_type, character_maximum_length, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = ANY(%s)
            ORDER BY column_name
            """,
            (TABLE_NAME, list(EXPECTED_COLUMNS)),
        )
        return [tuple(row) for row in cursor.fetchall()]


def _all_target_column_names(connection) -> list[str]:  # type: ignore[no-untyped-def]
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = ANY(%s)
            """,
            (TABLE_NAME, list(EXPECTED_COLUMNS)),
        )
        return [str(row[0]) for row in cursor.fetchall()]


def _version(connection) -> str:  # type: ignore[no-untyped-def]
    with connection.cursor() as cursor:
        cursor.execute("SELECT version_num FROM alembic_version")
        rows = cursor.fetchall()
    if len(rows) != 1:
        raise ProbeError(f"expected one Alembic version row, got {len(rows)}")
    return str(rows[0][0])


def _run_alembic(database_url: str, *arguments: str) -> None:
    repo_root = Path(__file__).resolve().parents[2]
    command = [sys.executable, "-m", "alembic", *arguments]
    try:
        result = subprocess.run(
            command,
            cwd=repo_root / "backend",
            env=alembic_environment(database_url),
            capture_output=True,
            text=True,
            check=False,
            timeout=ALEMBIC_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as exc:
        raise ProbeError(
            f"alembic {' '.join(arguments)} timed out after "
            f"{ALEMBIC_TIMEOUT_SECONDS}s"
        ) from exc
    if result.returncode != 0:
        output = "\n".join(part for part in (result.stdout, result.stderr) if part)
        raise ProbeError(
            f"alembic {' '.join(arguments)} failed with exit {result.returncode}\n"
            f"{output}"
        )


def _drop_database(admin_connection, database_name: str) -> None:  # type: ignore[no-untyped-def]
    if not is_safe_scratch_database_name(database_name):
        raise ProbeError(
            f"refusing to drop unrecognised scratch database {database_name!r}"
        )
    admin_connection.autocommit = True
    with admin_connection.cursor() as cursor:
        cursor.execute(
            sql.SQL("SET statement_timeout = {}").format(
                sql.Literal(STATEMENT_TIMEOUT_MS)
            )
        )
        cursor.execute(
            sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(
                sql.Identifier(database_name)
            )
        )


def _cleanup_scratch_database(
    admin_database_url: str, database_name: str, admin_connection: Any
) -> ProbeError | None:
    """Drop the generated database through a fresh admin connection when possible."""
    if not is_safe_scratch_database_name(database_name):
        raise ProbeError(
            f"refusing to clean up unrecognised scratch database {database_name!r}"
        )

    cleanup_errors: list[BaseException] = []
    fresh_connection: Any = None
    try:
        try:
            fresh_connection = _connect(admin_database_url)
            _drop_database(fresh_connection, database_name)
        except BaseException:
            # If a create connection was already established, try it as a
            # fallback. DROP ... IF EXISTS makes this retry harmless.
            if admin_connection is None:
                cleanup_errors.append(RuntimeError("fresh cleanup connection failed"))
            else:
                try:
                    _drop_database(admin_connection, database_name)
                except BaseException as fallback_error:
                    cleanup_errors.append(fallback_error)
        finally:
            if (
                fresh_connection is not None
                and fresh_connection is not admin_connection
            ):
                try:
                    fresh_connection.close()
                except BaseException as close_error:
                    cleanup_errors.append(close_error)
            if admin_connection is not None:
                try:
                    admin_connection.close()
                except BaseException as close_error:
                    cleanup_errors.append(close_error)
    except BaseException as cleanup_error:
        cleanup_errors.append(cleanup_error)

    if cleanup_errors:
        return ProbeError("scratch database cleanup failed")
    return None


class _SignalScope:
    """Scoped handlers that defer termination for the whole probe lifecycle."""

    _SIGNALS = (signal.SIGTERM, signal.SIGINT)

    def __init__(self) -> None:
        self._previous: dict[signal.Signals, Any] = {
            signum: signal.getsignal(signum) for signum in self._SIGNALS
        }
        self._installed: list[signal.Signals] = []
        self._pending: list[int] = []
        self._cleanup_started = False

    def install(self) -> None:
        try:
            for signum in self._SIGNALS:
                signal.signal(signum, self._handle)
                self._installed.append(signum)
        except BaseException:
            self.restore()
            raise

    def begin_cleanup(self) -> None:
        """Mark cleanup for callers while keeping the handler fully deferred."""
        self._cleanup_started = True

    def pending_signal_names(self) -> tuple[str, ...]:
        return tuple(signal.Signals(signum).name for signum in self._pending)

    def _handle(self, signum: int, _frame: object) -> None:
        # Never raise from a signal handler.  An asynchronous exception here
        # can land between the operation's ``except`` and ``finally`` blocks,
        # or while cleanup is being entered, which would leak the scratch DB.
        signum_value = int(signum)
        if signum_value not in self._pending:
            self._pending.append(signum_value)

    def restore(self) -> None:
        restoration_error: BaseException | None = None
        for signum in reversed(self._installed):
            try:
                signal.signal(signum, self._previous[signum])
            except BaseException as exc:
                if restoration_error is None:
                    restoration_error = exc
        self._installed.clear()
        if restoration_error is not None:
            raise restoration_error


@contextmanager
def _scoped_signal_handlers() -> Iterator[_SignalScope]:
    """Keep termination handlers installed until guarded cleanup is complete."""
    scope = _SignalScope()
    scope.install()
    try:
        yield scope
    finally:
        scope.restore()


def run_probe(admin_database_url: str) -> None:
    """Run the exact-parent upgrade/downgrade probe and always clean up."""
    database_name = scratch_database_name()
    if not is_safe_scratch_database_name(database_name):
        raise ProbeError(
            f"refusing to use unrecognised scratch database {database_name!r}"
        )
    admin_connection: Any = None
    operation_failure: BaseException | None = None
    cleanup_failure: BaseException | None = None
    scope: _SignalScope | None = None
    try:
        with _scoped_signal_handlers() as scope:
            try:
                admin_connection = _connect(admin_database_url)
                _create_database(admin_connection, database_name)
                database_url = _scratch_database_url(admin_database_url, database_name)

                connection = _connect(database_url)
                try:
                    _create_prior_state(connection)
                    if _version(connection) != PARENT_REVISION:
                        raise ProbeError(
                            "scratch database did not start at the exact parent revision"
                        )
                    verify_columns_absent(_all_target_column_names(connection))
                finally:
                    connection.close()

                _run_alembic(database_url, "upgrade", TARGET_REVISION)
                connection = _connect(database_url)
                try:
                    if _version(connection) != TARGET_REVISION:
                        raise ProbeError(
                            "upgrade did not record the target Alembic revision"
                        )
                    verify_added_columns(_column_rows(connection))
                finally:
                    connection.close()

                _run_alembic(database_url, "downgrade", PARENT_REVISION)
                connection = _connect(database_url)
                try:
                    if _version(connection) != PARENT_REVISION:
                        raise ProbeError(
                            "downgrade did not restore the exact parent revision"
                        )
                    verify_columns_absent(_all_target_column_names(connection))
                finally:
                    connection.close()
            except BaseException as exc:
                operation_failure = exc
            finally:
                scope.begin_cleanup()
                try:
                    cleanup_failure = _cleanup_scratch_database(
                        admin_database_url, database_name, admin_connection
                    )
                except BaseException as exc:
                    cleanup_failure = ProbeError("scratch database cleanup failed")
                    cleanup_failure.__cause__ = exc
    except BaseException as exc:
        if operation_failure is None:
            operation_failure = exc

    def safe_failure_message(failure: BaseException) -> str:
        return _redact_credentials(str(failure), (admin_database_url,))

    pending_signal_names = scope.pending_signal_names() if scope is not None else ()
    if pending_signal_names:
        context: list[str] = []
        if operation_failure is not None:
            context.append(
                f"operation failed: {safe_failure_message(operation_failure)}"
            )
        if cleanup_failure is not None:
            context.append(f"cleanup failed: {cleanup_failure}")
        context.append(f"received {', '.join(pending_signal_names)}")
        raise ProbeInterrupted("; ".join(context))
    if operation_failure is not None and cleanup_failure is not None:
        raise ProbeError(
            f"{safe_failure_message(operation_failure)}; cleanup failed: {cleanup_failure}"
        ) from operation_failure
    if operation_failure is not None:
        safe_message = safe_failure_message(operation_failure)
        if safe_message != str(operation_failure):
            raise ProbeError(safe_message) from operation_failure
        raise operation_failure
    if cleanup_failure is not None:
        raise cleanup_failure


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--admin-database-url",
        default=None,
        help="PostgreSQL URL with permission to create/drop the generated scratch DB",
    )
    parser.add_argument(
        "--alembic-command",
        nargs=argparse.REMAINDER,
        help="run an Alembic command using the standard PG* environment fields",
    )
    args = parser.parse_args(argv)
    if args.alembic_command is not None and not args.alembic_command:
        parser.error("--alembic-command requires at least one Alembic argument")
    return args


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    diagnostic_urls: list[str] = []
    try:
        if args.alembic_command is not None:
            database_url = postgres_url_from_environment()
            diagnostic_urls.append(database_url)
            _run_alembic(database_url, *args.alembic_command)
            print(f"Alembic {' '.join(args.alembic_command)} passed")
            return 0
        admin_database_url = args.admin_database_url or postgres_url_from_environment()
        diagnostic_urls.append(admin_database_url)
        run_probe(admin_database_url)
    except Exception as exc:
        label = (
            "Alembic command"
            if args.alembic_command is not None
            else "Targeted evidence migration probe"
        )
        print(
            f"{label} failed: {_redact_credentials(str(exc), diagnostic_urls)}",
            file=sys.stderr,
        )
        return 1
    print(
        "Targeted evidence migration probe passed: "
        f"{PARENT_REVISION} -> {TARGET_REVISION} -> {PARENT_REVISION}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
