#!/usr/bin/env python3
"""Probe the evidence migration's upgrade and downgrade delta in isolation.

This is deliberately not an ``alembic upgrade head`` check.  The historical
revision chain is measured separately and remains advisory because it contains
known bootstrap debt.  This probe creates only the two objects required to
exercise ``evidence_prov_20260816`` from its exact parent revision, runs the
real Alembic commands, verifies the PostgreSQL column metadata, and removes its
generated database in a ``finally`` block.
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import subprocess
import sys
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import TypeAlias

import psycopg2  # type: ignore[import-untyped]
from psycopg2 import sql  # type: ignore[import-untyped]
from sqlalchemy.engine import make_url

PARENT_REVISION = "i9j0k1l2m3n4"
TARGET_REVISION = "evidence_prov_20260816"
TABLE_NAME = "stance_classifications"
SCRATCH_DATABASE_PREFIX = "ci_evidence_delta_"

ColumnRow: TypeAlias = tuple[str, str, int | None, str]

EXPECTED_COLUMNS: dict[str, tuple[str, int | None]] = {
    "claim_text": ("text", None),
    "source_content_hash": ("character varying", 64),
}

_SCRATCH_DATABASE_RE = re.compile(
    rf"^{re.escape(SCRATCH_DATABASE_PREFIX)}[0-9]+_[a-z0-9_]+_[0-9a-f]{{8}}$"
)


class ProbeError(RuntimeError):
    """Raised when the targeted migration contract is not satisfied."""


def scratch_database_name(label: str = "probe") -> str:
    """Return a unique, deliberately recognisable PostgreSQL database name."""
    safe_label = re.sub(r"[^a-z0-9]+", "_", label.lower()).strip("_") or "probe"
    safe_label = safe_label[:24].rstrip("_") or "probe"
    return f"{SCRATCH_DATABASE_PREFIX}{os.getpid()}_{safe_label}_{secrets.token_hex(4)}"


def is_safe_scratch_database_name(name: str) -> bool:
    """Allow destructive cleanup only for names generated by this probe."""
    return bool(_SCRATCH_DATABASE_RE.fullmatch(name))


def verify_added_columns(rows: Iterable[ColumnRow]) -> None:
    """Verify the exact nullable PostgreSQL types added by the migration."""
    observed = {
        name: (data_type, character_maximum_length, is_nullable)
        for name, data_type, character_maximum_length, is_nullable in rows
    }
    for name, (expected_type, expected_length) in EXPECTED_COLUMNS.items():
        expected = (expected_type, expected_length, "YES")
        actual = observed.get(name)
        if actual != expected:
            raise ProbeError(
                f"{TABLE_NAME}.{name} metadata mismatch: "
                f"expected {expected!r}, got {actual!r}"
            )


def verify_columns_absent(column_names: Iterable[str]) -> None:
    """Verify neither migration column remains after the downgrade."""
    unexpected = sorted(set(column_names).intersection(EXPECTED_COLUMNS))
    if unexpected:
        raise ProbeError(
            f"downgrade left migration column(s) on {TABLE_NAME}: "
            f"{', '.join(unexpected)}"
        )


def alembic_environment(
    database_url: str, base_environment: Mapping[str, str] | None = None
) -> dict[str, str]:
    """Build an Alembic environment that cannot fall through to managed DBs."""
    environment = dict(os.environ if base_environment is None else base_environment)
    environment["DATABASE_URL"] = database_url
    # env.py prefers SUPABASE_DB_URL. An empty value makes the target explicit.
    environment["SUPABASE_DB_URL"] = ""
    environment.setdefault("ENVIRONMENT", "testing")
    backend_root = Path(__file__).resolve().parents[2] / "backend"
    python_path = environment.get("PYTHONPATH")
    environment["PYTHONPATH"] = (
        str(backend_root)
        if not python_path
        else os.pathsep.join((str(backend_root), python_path))
    )
    return environment


def _scratch_database_url(admin_database_url: str, database_name: str) -> str:
    parsed = make_url(admin_database_url)
    if parsed.drivername not in {"postgresql", "postgresql+psycopg2"}:
        raise ProbeError(
            "targeted evidence migration probe requires a PostgreSQL admin URL"
        )
    return parsed.set(database=database_name).render_as_string(hide_password=False)


def _connect(database_url: str):  # type: ignore[no-untyped-def]
    return psycopg2.connect(database_url)


def _create_prior_state(connection) -> None:  # type: ignore[no-untyped-def]
    """Create only the explicit parent-state objects needed by the migration."""
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE alembic_version (
                version_num VARCHAR(32) NOT NULL
            )
            """)
        cursor.execute(
            "INSERT INTO alembic_version (version_num) VALUES (%s)",
            (PARENT_REVISION,),
        )
        cursor.execute("""
            CREATE TABLE stance_classifications (
                id UUID PRIMARY KEY
            )
            """)
    connection.commit()


def _column_rows(connection) -> list[ColumnRow]:  # type: ignore[no-untyped-def]
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name, data_type, character_maximum_length, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = ANY(%s)
            ORDER BY column_name
            """,
            (TABLE_NAME, list(EXPECTED_COLUMNS)),
        )
        return [tuple(row) for row in cursor.fetchall()]


def _all_target_column_names(connection) -> list[str]:  # type: ignore[no-untyped-def]
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = ANY(%s)
            """,
            (TABLE_NAME, list(EXPECTED_COLUMNS)),
        )
        return [str(row[0]) for row in cursor.fetchall()]


def _version(connection) -> str:  # type: ignore[no-untyped-def]
    with connection.cursor() as cursor:
        cursor.execute("SELECT version_num FROM alembic_version")
        rows = cursor.fetchall()
    if len(rows) != 1:
        raise ProbeError(f"expected one Alembic version row, got {len(rows)}")
    return str(rows[0][0])


def _run_alembic(database_url: str, *arguments: str) -> None:
    repo_root = Path(__file__).resolve().parents[2]
    result = subprocess.run(
        [sys.executable, "-m", "alembic", *arguments],
        cwd=repo_root / "backend",
        env=alembic_environment(database_url),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        output = "\n".join(part for part in (result.stdout, result.stderr) if part)
        raise ProbeError(
            f"alembic {' '.join(arguments)} failed with exit {result.returncode}\n"
            f"{output}"
        )


def _drop_database(admin_connection, database_name: str) -> None:  # type: ignore[no-untyped-def]
    if not is_safe_scratch_database_name(database_name):
        raise ProbeError(
            f"refusing to drop unrecognised scratch database {database_name!r}"
        )
    admin_connection.autocommit = True
    with admin_connection.cursor() as cursor:
        cursor.execute(
            sql.SQL("DROP DATABASE {} WITH (FORCE)").format(
                sql.Identifier(database_name)
            )
        )


def run_probe(admin_database_url: str) -> None:
    """Run the exact-parent upgrade/downgrade probe and always clean up."""
    database_name = scratch_database_name()
    admin_connection = None
    scratch_created = False
    failure: Exception | None = None
    try:
        admin_connection = _connect(admin_database_url)
        admin_connection.autocommit = True
        with admin_connection.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE DATABASE {} WITH TEMPLATE template0").format(
                    sql.Identifier(database_name)
                )
            )
        scratch_created = True
        database_url = _scratch_database_url(admin_database_url, database_name)

        connection = _connect(database_url)
        try:
            _create_prior_state(connection)
            if _version(connection) != PARENT_REVISION:
                raise ProbeError(
                    "scratch database did not start at the exact parent revision"
                )
            verify_columns_absent(_all_target_column_names(connection))
        finally:
            connection.close()

        _run_alembic(database_url, "upgrade", TARGET_REVISION)
        connection = _connect(database_url)
        try:
            if _version(connection) != TARGET_REVISION:
                raise ProbeError("upgrade did not record the target Alembic revision")
            verify_added_columns(_column_rows(connection))
        finally:
            connection.close()

        _run_alembic(database_url, "downgrade", PARENT_REVISION)
        connection = _connect(database_url)
        try:
            if _version(connection) != PARENT_REVISION:
                raise ProbeError("downgrade did not restore the exact parent revision")
            verify_columns_absent(_all_target_column_names(connection))
        finally:
            connection.close()
    except Exception as exc:
        failure = exc
    finally:
        if admin_connection is not None and scratch_created:
            try:
                _drop_database(admin_connection, database_name)
            except Exception as cleanup_error:
                if failure is None:
                    failure = ProbeError(
                        f"scratch database cleanup failed: {cleanup_error}"
                    )
        if admin_connection is not None:
            admin_connection.close()
    if failure is not None:
        raise failure


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--admin-database-url",
        default=os.environ.get("DATABASE_URL"),
        help="PostgreSQL URL with permission to create/drop the generated scratch DB",
    )
    args = parser.parse_args(argv)
    if not args.admin_database_url:
        parser.error("--admin-database-url or DATABASE_URL is required")
    return args


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        run_probe(args.admin_database_url)
    except Exception as exc:
        print(f"Targeted evidence migration probe failed: {exc}", file=sys.stderr)
        return 1
    print(
        "Targeted evidence migration probe passed: "
        f"{PARENT_REVISION} -> {TARGET_REVISION} -> {PARENT_REVISION}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
