apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nous-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nous-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nous-platform

  # Points at the directory containing staging.yaml and production.yaml
  source:
    repoURL: https://github.com/Goodwiinz/rag.git
    targetRevision: develop
    path: infrastructure/argocd/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
