"""Initial migration

Revision ID: 258df00ea837
Revises: 
Create Date: 2025-10-09 04:24:10.973137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '258df00ea837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-10-08 20:56:33.824505+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###