"""Add chat_messages.plan_reasoning

Revision ID: add_chat_messages_plan_reasoning
Revises: evidence_prov_20260816
Create Date: 2026-08-18 00:00:00.000000

Persists the planner's top-level rationale string for the turn's advisory
plan (chat_messages.plan), previously generated by the model and discarded.
Capped to 2000 chars by planner_node before it reaches this column.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "add_chat_messages_plan_reasoning"
down_revision = "evidence_prov_20260816"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "chat_messages",
        sa.Column("plan_reasoning", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("chat_messages", "plan_reasoning")
