"""Enhance document processing with multimodal support and quality metrics

Revision ID: f931599b6b5b
Revises: 258df00ea837
Create Date: 2025-10-16 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f931599b6b5b'
down_revision = '258df00ea837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, create new enum types (only if they don't exist)
    op.execute("DO $$ BEGIN CREATE TYPE processingstage AS ENUM ('uploaded', 'validated', 'extracted', 'analyzed', 'indexed', 'embedded', 'completed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE contenttype AS ENUM ('text', 'image', 'audio', 'video', 'metadata'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE qualitymetrictype AS ENUM ('text_clarity', 'image_resolution', 'audio_clarity', 'video_quality', 'content_richness', 'extraction_accuracy'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")

    # Create processing_history table
    op.create_table('processing_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('stage', sa.Enum('uploaded', 'validated', 'extracted', 'analyzed', 'indexed', 'embedded', 'completed', name='processingstage', create_type=False), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('processor_id', sa.String(length=255), nullable=True),
        sa.Column('processing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_type', sa.String(length=100), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('cpu_time_seconds', sa.Float(), nullable=True),
        sa.Column('memory_peak_mb', sa.Float(), nullable=True),
        sa.Column('progress_percentage', sa.Float(), nullable=False),
        sa.Column('current_step', sa.String(length=255), nullable=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('duration_seconds >= 0', name='check_duration_positive'),
        sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='check_progress_range'),
        sa.CheckConstraint('retry_count >= 0', name='check_retry_non_negative')
    )
    op.create_index(op.f('ix_processing_history_document_id'), 'processing_history', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_history_stage'), 'processing_history', ['stage'], unique=False)

    # Create document_versions table
    op.create_table('document_versions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('version_label', sa.String(length=100), nullable=True),
        sa.Column('change_description', sa.Text(), nullable=True),
        sa.Column('is_major_version', sa.Boolean(), nullable=False),
        sa.Column('is_current_version', sa.Boolean(), nullable=False),
        sa.Column('file_path', sa.String(length=1000), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('content_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('changed_sections', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('version_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('parent_version_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['parent_version_id'], ['document_versions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('file_size_bytes >= 0', name='check_file_size_positive'),
        sa.CheckConstraint('version_number > 0', name='check_version_positive')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)

    # Create multimodal_content table
    op.create_table('multimodal_content',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('document_version_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('content_type', sa.Enum('text', 'image', 'audio', 'video', 'metadata', name='contenttype', create_type=False), nullable=False),
        sa.Column('content_id', sa.String(length=255), nullable=False),
        sa.Column('sequence_order', sa.Integer(), nullable=False),
        sa.Column('raw_content', sa.Text(), nullable=True),
        sa.Column('processed_content', sa.Text(), nullable=True),
        sa.Column('content_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('extraction_method', sa.String(length=100), nullable=True),
        sa.Column('extraction_confidence', sa.Float(), nullable=True),
        sa.Column('media_duration_seconds', sa.Float(), nullable=True),
        sa.Column('media_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('media_format', sa.String(length=50), nullable=True),
        sa.Column('language_code', sa.String(length=10), nullable=True),
        sa.Column('word_count', sa.Integer(), nullable=True),
        sa.Column('character_count', sa.Integer(), nullable=True),
        sa.Column('is_indexed', sa.Boolean(), nullable=False),
        sa.Column('embedding_id', sa.String(length=255), nullable=True),
        sa.Column('search_vector', sa.Text(), nullable=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('character_count >= 0', name='check_character_count_positive'),
        sa.CheckConstraint('extraction_confidence >= 0 AND extraction_confidence <= 1', name='check_extraction_confidence_range'),
        sa.CheckConstraint('media_duration_seconds >= 0', name='check_media_duration_positive'),
        sa.CheckConstraint('quality_score >= 0 AND quality_score <= 1', name='check_quality_score_range'),
        sa.CheckConstraint('sequence_order >= 0', name='check_sequence_order_positive'),
        sa.CheckConstraint('word_count >= 0', name='check_word_count_positive')
    )
    op.create_index(op.f('ix_multimodal_content_content_id'), 'multimodal_content', ['content_id'], unique=False)
    op.create_index(op.f('ix_multimodal_content_content_type'), 'multimodal_content', ['content_type'], unique=False)
    op.create_index(op.f('ix_multimodal_content_document_id'), 'multimodal_content', ['document_id'], unique=False)
    op.create_index(op.f('ix_multimodal_content_embedding_id'), 'multimodal_content', ['embedding_id'], unique=False)

    # Create document_quality_metrics table
    op.create_table('document_quality_metrics',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('content_id', sa.String(length=255), nullable=True),
        sa.Column('metric_type', sa.Enum('text_clarity', 'image_resolution', 'audio_clarity', 'video_quality', 'content_richness', 'extraction_accuracy', name='qualitymetrictype', create_type=False), nullable=False),
        sa.Column('metric_value', sa.Float(), nullable=False),
        sa.Column('metric_unit', sa.String(length=50), nullable=True),
        sa.Column('assessment_method', sa.String(length=100), nullable=True),
        sa.Column('assessment_version', sa.String(length=50), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('threshold_min', sa.Float(), nullable=True),
        sa.Column('threshold_max', sa.Float(), nullable=True),
        sa.Column('threshold_target', sa.Float(), nullable=True),
        sa.Column('meets_threshold', sa.Boolean(), nullable=True),
        sa.Column('metric_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('comparison_baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('assessed_by_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('assessment_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['assessed_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='check_confidence_score_range'),
        sa.CheckConstraint('metric_value >= 0', name='check_metric_value_positive')
    )
    op.create_index(op.f('ix_document_quality_metrics_content_id'), 'document_quality_metrics', ['content_id'], unique=False)
    op.create_index(op.f('ix_document_quality_metrics_document_id'), 'document_quality_metrics', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_quality_metrics_meets_threshold'), 'document_quality_metrics', ['meets_threshold'], unique=False)
    op.create_index(op.f('ix_document_quality_metrics_metric_type'), 'document_quality_metrics', ['metric_type'], unique=False)

    # Create document_access_log table
    op.create_table('document_access_log',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('document_version_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('access_type', sa.String(length=50), nullable=False),
        sa.Column('access_result', sa.String(length=20), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('api_key_id', sa.String(length=255), nullable=True),
        sa.Column('request_method', sa.String(length=10), nullable=True),
        sa.Column('request_path', sa.String(length=1000), nullable=True),
        sa.Column('request_query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('referer', sa.String(length=1000), nullable=True),
        sa.Column('response_status_code', sa.Integer(), nullable=True),
        sa.Column('response_size_bytes', sa.Integer(), nullable=True),
        sa.Column('response_time_ms', sa.Float(), nullable=True),
        sa.Column('is_suspicious', sa.Boolean(), nullable=False),
        sa.Column('threat_score', sa.Float(), nullable=True),
        sa.Column('security_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('access_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('response_size_bytes >= 0', name='check_response_size_positive'),
        sa.CheckConstraint('response_time_ms >= 0', name='check_response_time_positive'),
        sa.CheckConstraint('threat_score >= 0 AND threat_score <= 1', name='check_threat_score_range')
    )
    op.create_index(op.f('ix_document_access_log_access_type'), 'document_access_log', ['access_type'], unique=False)
    op.create_index(op.f('ix_document_access_log_api_key_id'), 'document_access_log', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_document_access_log_document_id'), 'document_access_log', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_log_ip_address'), 'document_access_log', ['ip_address'], unique=False)
    op.create_index(op.f('ix_document_access_log_is_suspicious'), 'document_access_log', ['is_suspicious'], unique=False)
    op.create_index(op.f('ix_document_access_log_session_id'), 'document_access_log', ['session_id'], unique=False)

    # Add new columns to existing documents table for enhanced processing
    op.add_column('documents', sa.Column('content_summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processing_retry_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('documents', sa.Column('embedding_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('is_embedded', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('documents', sa.Column('is_indexed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('documents', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by_user_id', postgresql.UUID(as_uuid=True), nullable=False))

    # Add indexes for documents table
    op.create_index('ix_documents_embedding_id', 'documents', ['embedding_id'], unique=False)
    op.create_index('ix_documents_is_embedded', 'documents', ['is_embedded'], unique=False)
    op.create_index('ix_documents_is_indexed', 'documents', ['is_indexed'], unique=False)
    op.create_index('ix_documents_is_public', 'documents', ['is_public'], unique=False)
    op.create_index('ix_documents_uploaded_by_user_id', 'documents', ['uploaded_by_user_id'], unique=False)

    # Add new columns to existing processing_jobs table for enhanced multimodal support
    op.add_column('processing_jobs', sa.Column('total_steps', sa.Integer(), nullable=True))
    op.add_column('processing_jobs', sa.Column('completed_steps', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('processing_jobs', sa.Column('memory_peak_mb', sa.Float(), nullable=True))
    op.add_column('processing_jobs', sa.Column('cpu_time_seconds', sa.Float(), nullable=True))
    op.add_column('processing_jobs', sa.Column('current_step', sa.String(length=255), nullable=True))
    op.add_column('processing_jobs', sa.Column('progress_percentage', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.add_column('processing_jobs', sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('processing_jobs', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('processing_jobs', sa.Column('queue_name', sa.String(length=100), nullable=True))
    op.add_column('processing_jobs', sa.Column('worker_id', sa.String(length=255), nullable=True))

    # Add indexes for processing_jobs table
    op.create_index('ix_processing_jobs_progress_percentage', 'processing_jobs', ['progress_percentage'], unique=False)
    op.create_index('ix_processing_jobs_queue_name', 'processing_jobs', ['queue_name'], unique=False)
    op.create_index('ix_processing_jobs_worker_id', 'processing_jobs', ['worker_id'], unique=False)

    # Create performance indexes for common query patterns
    # Document processing queries
    op.create_index('idx_documents_org_status_processing', 'documents', ['organization_id', 'processing_status', 'document_type'])
    op.create_index('idx_documents_processing_queue', 'documents', ['processing_status', 'created_at', 'organization_id'])
    op.create_index('idx_documents_searchable', 'documents', ['is_embedded', 'is_indexed', 'is_deleted', 'organization_id'])

    # Processing history queries
    op.create_index('idx_processing_history_document_stage', 'processing_history', ['document_id', 'stage', 'created_at'])
    op.create_index('idx_processing_history_org_status', 'processing_history', ['organization_id', 'status', 'stage'])

    # Multimodal content queries
    op.create_index('idx_multimodal_content_document_type', 'multimodal_content', ['document_id', 'content_type', 'sequence_order'])
    op.create_index('idx_multimodal_content_indexed', 'multimodal_content', ['is_indexed', 'content_type', 'organization_id'])

    # Quality metrics queries
    op.create_index('idx_quality_metrics_document_type', 'document_quality_metrics', ['document_id', 'metric_type', 'created_at'])
    op.create_index('idx_quality_metrics_threshold', 'document_quality_metrics', ['meets_threshold', 'metric_type', 'organization_id'])

    # Access log queries
    op.create_index('idx_access_log_document_time', 'document_access_log', ['document_id', 'created_at'])
    op.create_index('idx_access_log_user_time', 'document_access_log', ['user_id', 'created_at'])
    op.create_index('idx_access_log_suspicious', 'document_access_log', ['is_suspicious', 'threat_score', 'created_at'])

    # Processing job queries
    op.create_index('idx_processing_jobs_queue_priority', 'processing_jobs', ['status', 'priority', 'created_at'])
    op.create_index('idx_processing_jobs_org_type', 'processing_jobs', ['organization_id', 'job_type', 'status'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop performance indexes
    op.drop_index('idx_processing_jobs_org_type', table_name='processing_jobs')
    op.drop_index('idx_processing_jobs_queue_priority', table_name='processing_jobs')
    op.drop_index('idx_access_log_suspicious', table_name='document_access_log')
    op.drop_index('idx_access_log_user_time', table_name='document_access_log')
    op.drop_index('idx_access_log_document_time', table_name='document_access_log')
    op.drop_index('idx_quality_metrics_threshold', table_name='document_quality_metrics')
    op.drop_index('idx_quality_metrics_document_type', table_name='document_quality_metrics')
    op.drop_index('idx_multimodal_content_indexed', table_name='multimodal_content')
    op.drop_index('idx_multimodal_content_document_type', table_name='multimodal_content')
    op.drop_index('idx_processing_history_org_status', table_name='processing_history')
    op.drop_index('idx_processing_history_document_stage', table_name='processing_history')
    op.drop_index('idx_documents_searchable', table_name='documents')
    op.drop_index('idx_documents_processing_queue', table_name='documents')
    op.drop_index('idx_documents_org_status_processing', table_name='documents')

    # Drop processing_jobs indexes
    op.drop_index('ix_processing_jobs_worker_id', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_queue_name', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_progress_percentage', table_name='processing_jobs')

    # Drop processing_jobs columns
    op.drop_column('processing_jobs', 'worker_id')
    op.drop_column('processing_jobs', 'queue_name')
    op.drop_column('processing_jobs', 'metrics')
    op.drop_column('processing_jobs', 'artifacts')
    op.drop_column('processing_jobs', 'progress_percentage')
    op.drop_column('processing_jobs', 'current_step')
    op.drop_column('processing_jobs', 'cpu_time_seconds')
    op.drop_column('processing_jobs', 'memory_peak_mb')
    op.drop_column('processing_jobs', 'completed_steps')
    op.drop_column('processing_jobs', 'total_steps')

    # Drop documents indexes
    op.drop_index('ix_documents_uploaded_by_user_id', table_name='documents')
    op.drop_index('ix_documents_is_public', table_name='documents')
    op.drop_index('ix_documents_is_indexed', table_name='documents')
    op.drop_index('ix_documents_is_embedded', table_name='documents')
    op.drop_index('ix_documents_embedding_id', table_name='documents')

    # Drop documents columns
    op.drop_column('documents', 'uploaded_by_user_id')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'is_public')
    op.drop_column('documents', 'is_indexed')
    op.drop_column('documents', 'is_embedded')
    op.drop_column('documents', 'embedding_id')
    op.drop_column('documents', 'processing_retry_count')
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'document_metadata')
    op.drop_column('documents', 'content_summary')

    # Drop document_access_log table
    op.drop_index(op.f('ix_document_access_log_session_id'), table_name='document_access_log')
    op.drop_index(op.f('ix_document_access_log_is_suspicious'), table_name='document_access_log')
    op.drop_index(op.f('ix_document_access_log_ip_address'), table_name='document_access_log')
    op.drop_index(op.f('ix_document_access_log_api_key_id'), table_name='document_access_log')
    op.drop_index(op.f('ix_document_access_log_access_type'), table_name='document_access_log')
    op.drop_table('document_access_log')

    # Drop document_quality_metrics table
    op.drop_index(op.f('ix_document_quality_metrics_metric_type'), table_name='document_quality_metrics')
    op.drop_index(op.f('ix_document_quality_metrics_meets_threshold'), table_name='document_quality_metrics')
    op.drop_index(op.f('ix_document_quality_metrics_content_id'), table_name='document_quality_metrics')
    op.drop_index(op.f('ix_document_quality_metrics_document_id'), table_name='document_quality_metrics')
    op.drop_table('document_quality_metrics')

    # Drop multimodal_content table
    op.drop_index(op.f('ix_multimodal_content_embedding_id'), table_name='multimodal_content')
    op.drop_index(op.f('ix_multimodal_content_document_id'), table_name='multimodal_content')
    op.drop_index(op.f('ix_multimodal_content_content_type'), table_name='multimodal_content')
    op.drop_index(op.f('ix_multimodal_content_content_id'), table_name='multimodal_content')
    op.drop_table('multimodal_content')

    # Drop document_versions table
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')

    # Drop processing_history table
    op.drop_index(op.f('ix_processing_history_stage'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_document_id'), table_name='processing_history')
    op.drop_table('processing_history')

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS qualitymetrictype")
    op.execute("DROP TYPE IF EXISTS contenttype")
    op.execute("DROP TYPE IF EXISTS processingstage")

    # ### end Alembic commands ###